# Generated by Django 3.2.9 on 2021-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Pesonal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phonenum', models.IntegerField()),
                ('customer_name', models.TextField()),
                ('customer_sex', models.TextField()),
                ('customer_birthdate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer_Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_phonenum', models.IntegerField()),
                ('employer_name', models.TextField()),
                ('employer_sex', models.TextField()),
                ('employer_birthdate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=10)),
                ('movie_name', models.TextField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('movie_explanation', models.TextField()),
                ('age_limit', models.CharField(max_length=2)),
                ('poster', models.ImageField(upload_to='')),
                ('grade', models.FloatField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_num', models.CharField(max_length=10)),
                ('movie_serial', models.CharField(max_length=10)),
                ('seat', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=10)),
                ('kind', models.TextField()),
                ('subtitle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_serial', models.CharField(max_length=10)),
                ('movie_id', models.CharField(max_length=10)),
                ('playtime', models.IntegerField()),
                ('theaternumber', models.CharField(max_length=3)),
                ('movie_price', models.IntegerField()),
            ],
        ),
    ]
